# Generated by Django 5.2 on 2025-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_business_name_remove_user_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_visitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('business', 'Business')], default='visitor', max_length=10),
        ),
        migrations.AlterField(
            model_name='visitorprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
