# Generated by Django 5.2 on 2025-04-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_business_user_is_visitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('visitor', 'Visitor'), ('business', 'Business')], max_length=10, null=True),
        ),
    ]
