# Generated by Django 5.2 on 2025-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='location',
            field=models.CharField(default='Jaffa, Tel Aviv', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(default='0500000000', max_length=20),
            preserve_default=False,
        ),
    ]
