# Generated by Django 5.2 on 2025-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_businessprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
