# Generated by Django 5.2 on 2025-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_businessprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorprofile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
