# Generated by Django 5.2 on 2025-04-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_visitorprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
