# Generated by Django 5.2 on 2025-05-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_address_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='work_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
