# Generated by Django 5.2 on 2025-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_businessprofile_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='work_time',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='work_time_fri',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='work_time_sat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='work_time_sun_thu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
