# Generated by Django 5.2 on 2025-05-20 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_businessprofile_work_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='accounts.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sale')},
            },
        ),
    ]
