# Generated by Django 5.2 on 2025-05-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_favoritesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='favorites_count',
            field=models.IntegerField(default=0),
        ),
    ]
