# Generated by Django 5.2 on 2025-05-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_sale_favorites_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_favorites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
