# Generated by Django 5.2 on 2025-05-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_sale_total_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_favorites',
            field=models.IntegerField(default=0),
        ),
    ]
