# Generated by Django 5.1.5 on 2025-06-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_offer_offerredemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerredemption',
            name='code',
            field=models.CharField(editable=False, max_length=5),
        ),
    ]
